### ISSUE TITLE
Illegal hardware instruction for `pytorch-arm-neoverse:r23.11-torch-2.1.0-onednn-acl`

### ISSUE THREAD

**Issue by Contextualist** [ARM-software/Tool-Solutions#217]
When I am running inference with libtorch from `armswdev/pytorch-arm-neoverse:r23.11-torch-2.1.0-onednn-acl`, the process crashed with `illegal hardware instruction (core dumped)`.

`armswdev/pytorch-arm-neoverse:r23.11-torch-2.1.0-openblas` works, and a while ago, `armswdev/pytorch-arm-neoverse:r23.06-torch-2.0.0-onednn-acl` also works. I haven't tested it against other images.

<details>
  <summary>Output of <code>lscpu</code></summary>

```
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           Neoverse-N1
    Model:              1
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r3p1
    BogoMIPS:           50.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-3
Vulnerabilities:        
  Gather data sampling: Not affected
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec rstack overflow: Not affected
  Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Mitigation; CSV2, BHB
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

</details>

**Comment by jondea** [comment]
Hi @Contextualist, thank you for the bug report. This is a known issue, and there's a fix in the works. It should be fixed for the next release, which will be out within the next week. @fadara01 has been looking into this, he might have more information.

The issue is that some build flags were set to native, and the image was built on a machine with SVE2. This means that on machines without SVE2, you get an illegal instruction error. One easy fix in the meantime is to build the docker image on the machine you want to run it on.

**Comment by Contextualist** [comment]
Thanks for the quick reply, and glad to know that this has already been taken care of!
